/** types/socket **/

export const types = {
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  HANDLE_MESSAGE: 'HANDLE_MESSAGE',
  HANDLE_ERROR: 'HANDLE_ERROR',
  SET_STATUS: 'SET_STATUS',
}
